-- finance_stream union views: real + synthetic behind fin_<table>_all
-- generated by `python -m finance_stream --emit-views postgres` — do not edit by hand.
-- assumes source tables in schema `world` and synthetic rows in `synth`.

CREATE OR REPLACE VIEW "fin_suppliers_all" AS
  SELECT * FROM world."fin_suppliers";

CREATE OR REPLACE VIEW "fin_staff_all" AS
  SELECT * FROM world."fin_staff";

CREATE OR REPLACE VIEW "fin_fee_schedule_all" AS
  SELECT * FROM world."fin_fee_schedule";

CREATE OR REPLACE VIEW "fin_price_list_all" AS
  SELECT * FROM world."fin_price_list";

CREATE OR REPLACE VIEW "fin_policy_all" AS
  SELECT * FROM world."fin_policy";

CREATE OR REPLACE VIEW "fin_purchase_orders_all" AS
  SELECT * FROM world."fin_purchase_orders"
  UNION ALL
  SELECT * FROM synth."fin_purchase_orders";

CREATE OR REPLACE VIEW "fin_po_lines_all" AS
  SELECT * FROM world."fin_po_lines"
  UNION ALL
  SELECT * FROM synth."fin_po_lines";

CREATE OR REPLACE VIEW "fin_goods_receipts_all" AS
  SELECT * FROM world."fin_goods_receipts"
  UNION ALL
  SELECT * FROM synth."fin_goods_receipts";

CREATE OR REPLACE VIEW "fin_invoices_all" AS
  SELECT * FROM world."fin_invoices"
  UNION ALL
  SELECT * FROM synth."fin_invoices";

CREATE OR REPLACE VIEW "fin_invoice_lines_all" AS
  SELECT * FROM world."fin_invoice_lines"
  UNION ALL
  SELECT * FROM synth."fin_invoice_lines";

CREATE OR REPLACE VIEW "fin_payments_out_all" AS
  SELECT * FROM world."fin_payments_out"
  UNION ALL
  SELECT * FROM synth."fin_payments_out";

CREATE OR REPLACE VIEW "fin_credit_memos_all" AS
  SELECT * FROM world."fin_credit_memos"
  UNION ALL
  SELECT * FROM synth."fin_credit_memos";

CREATE OR REPLACE VIEW "fin_register_txns_all" AS
  SELECT * FROM world."fin_register_txns"
  UNION ALL
  SELECT * FROM synth."fin_register_txns";

CREATE OR REPLACE VIEW "fin_register_totals_all" AS
  SELECT * FROM world."fin_register_totals"
  UNION ALL
  SELECT * FROM synth."fin_register_totals";

CREATE OR REPLACE VIEW "fin_card_mix_all" AS
  SELECT * FROM world."fin_card_mix"
  UNION ALL
  SELECT * FROM synth."fin_card_mix";

CREATE OR REPLACE VIEW "fin_cash_counts_all" AS
  SELECT * FROM world."fin_cash_counts"
  UNION ALL
  SELECT * FROM synth."fin_cash_counts";

CREATE OR REPLACE VIEW "fin_paid_outs_all" AS
  SELECT * FROM world."fin_paid_outs"
  UNION ALL
  SELECT * FROM synth."fin_paid_outs";

CREATE OR REPLACE VIEW "fin_bank_settlements_all" AS
  SELECT * FROM world."fin_bank_settlements"
  UNION ALL
  SELECT * FROM synth."fin_bank_settlements";

CREATE OR REPLACE VIEW "fin_settlement_adjustments_all" AS
  SELECT * FROM world."fin_settlement_adjustments"
  UNION ALL
  SELECT * FROM synth."fin_settlement_adjustments";
