-- finance_stream union views: real + synthetic behind fin_<table>_all
-- generated by `python -m finance_stream --emit-views sqlite` — do not edit by hand.
-- assumes a sqlite file written with `--sink sqlite --seed-source`
--   (real tables copied in as world_<t>, synthetic as synth_<t>).

DROP VIEW IF EXISTS "fin_suppliers_all";
CREATE VIEW "fin_suppliers_all" AS
  SELECT * FROM "world_fin_suppliers";

DROP VIEW IF EXISTS "fin_staff_all";
CREATE VIEW "fin_staff_all" AS
  SELECT * FROM "world_fin_staff";

DROP VIEW IF EXISTS "fin_fee_schedule_all";
CREATE VIEW "fin_fee_schedule_all" AS
  SELECT * FROM "world_fin_fee_schedule";

DROP VIEW IF EXISTS "fin_price_list_all";
CREATE VIEW "fin_price_list_all" AS
  SELECT * FROM "world_fin_price_list";

DROP VIEW IF EXISTS "fin_policy_all";
CREATE VIEW "fin_policy_all" AS
  SELECT * FROM "world_fin_policy";

DROP VIEW IF EXISTS "fin_purchase_orders_all";
CREATE VIEW "fin_purchase_orders_all" AS
  SELECT * FROM "world_fin_purchase_orders"
  UNION ALL
  SELECT * FROM "synth_fin_purchase_orders";

DROP VIEW IF EXISTS "fin_po_lines_all";
CREATE VIEW "fin_po_lines_all" AS
  SELECT * FROM "world_fin_po_lines"
  UNION ALL
  SELECT * FROM "synth_fin_po_lines";

DROP VIEW IF EXISTS "fin_goods_receipts_all";
CREATE VIEW "fin_goods_receipts_all" AS
  SELECT * FROM "world_fin_goods_receipts"
  UNION ALL
  SELECT * FROM "synth_fin_goods_receipts";

DROP VIEW IF EXISTS "fin_invoices_all";
CREATE VIEW "fin_invoices_all" AS
  SELECT * FROM "world_fin_invoices"
  UNION ALL
  SELECT * FROM "synth_fin_invoices";

DROP VIEW IF EXISTS "fin_invoice_lines_all";
CREATE VIEW "fin_invoice_lines_all" AS
  SELECT * FROM "world_fin_invoice_lines"
  UNION ALL
  SELECT * FROM "synth_fin_invoice_lines";

DROP VIEW IF EXISTS "fin_payments_out_all";
CREATE VIEW "fin_payments_out_all" AS
  SELECT * FROM "world_fin_payments_out"
  UNION ALL
  SELECT * FROM "synth_fin_payments_out";

DROP VIEW IF EXISTS "fin_credit_memos_all";
CREATE VIEW "fin_credit_memos_all" AS
  SELECT * FROM "world_fin_credit_memos"
  UNION ALL
  SELECT * FROM "synth_fin_credit_memos";

DROP VIEW IF EXISTS "fin_register_txns_all";
CREATE VIEW "fin_register_txns_all" AS
  SELECT * FROM "world_fin_register_txns"
  UNION ALL
  SELECT * FROM "synth_fin_register_txns";

DROP VIEW IF EXISTS "fin_register_totals_all";
CREATE VIEW "fin_register_totals_all" AS
  SELECT * FROM "world_fin_register_totals"
  UNION ALL
  SELECT * FROM "synth_fin_register_totals";

DROP VIEW IF EXISTS "fin_card_mix_all";
CREATE VIEW "fin_card_mix_all" AS
  SELECT * FROM "world_fin_card_mix"
  UNION ALL
  SELECT * FROM "synth_fin_card_mix";

DROP VIEW IF EXISTS "fin_cash_counts_all";
CREATE VIEW "fin_cash_counts_all" AS
  SELECT * FROM "world_fin_cash_counts"
  UNION ALL
  SELECT * FROM "synth_fin_cash_counts";

DROP VIEW IF EXISTS "fin_paid_outs_all";
CREATE VIEW "fin_paid_outs_all" AS
  SELECT * FROM "world_fin_paid_outs"
  UNION ALL
  SELECT * FROM "synth_fin_paid_outs";

DROP VIEW IF EXISTS "fin_bank_settlements_all";
CREATE VIEW "fin_bank_settlements_all" AS
  SELECT * FROM "world_fin_bank_settlements"
  UNION ALL
  SELECT * FROM "synth_fin_bank_settlements";

DROP VIEW IF EXISTS "fin_settlement_adjustments_all";
CREATE VIEW "fin_settlement_adjustments_all" AS
  SELECT * FROM "world_fin_settlement_adjustments"
  UNION ALL
  SELECT * FROM "synth_fin_settlement_adjustments";
