"""Union view DDL: expose real + synthetic finance data behind one name.

A consuming app/agent (e.g. Penny) can point its tools at ``fin_<table>_all``
instead of the raw table and transparently see source rows plus everything the
stream has generated. Because the synthetic tables share the source's exact
column layout and continue its id sequences, each view is a plain ``UNION ALL``.

The 14 tables the generator writes to get real+synthetic union views; the 5
dimension tables (never generated) get passthrough views so ``_all`` works
uniformly everywhere.
"""
from __future__ import annotations

from . import schema

# dimensions are read from source, never generated -> passthrough, not union
DIMENSIONS = {
    "fin_suppliers", "fin_staff", "fin_fee_schedule", "fin_price_list", "fin_policy",
}
GENERATED = [t for t in schema.TABLES if t not in DIMENSIONS]


def build_views(dialect: str, *, synth_prefix: str = "synth_") -> str:
    if dialect not in ("postgres", "sqlite"):
        raise ValueError(f"unknown dialect: {dialect}")

    header = (
        "-- finance_stream union views: real + synthetic behind fin_<table>_all\n"
        "-- generated by `python -m finance_stream --emit-views "
        f"{dialect}` — do not edit by hand.\n"
    )
    if dialect == "postgres":
        header += "-- assumes source tables in schema `world` and synthetic rows in `synth`.\n"
    else:
        header += ("-- assumes a sqlite file written with `--sink sqlite --seed-source`\n"
                   f"--   (real tables copied in as world_<t>, synthetic as {synth_prefix}<t>).\n")

    blocks: list[str] = []
    for t in schema.TABLES:
        view = f"{t}_all"
        if dialect == "postgres":
            real = f'SELECT * FROM world."{t}"'
            if t in DIMENSIONS:
                body = real
            else:
                body = f'{real}\n  UNION ALL\n  SELECT * FROM synth."{t}"'
            blocks.append(f'CREATE OR REPLACE VIEW "{view}" AS\n  {body};')
        else:  # sqlite
            real = f'SELECT * FROM "world_{t}"'
            if t in DIMENSIONS:
                body = real
            else:
                body = f'{real}\n  UNION ALL\n  SELECT * FROM "{synth_prefix}{t}"'
            blocks.append(f'DROP VIEW IF EXISTS "{view}";\nCREATE VIEW "{view}" AS\n  {body};')

    return header + "\n" + "\n\n".join(blocks) + "\n"
